steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'europe-southwest1-docker.pkg.dev/${PROJECT_ID}/myimage:${SHORT_SHA}', '.']

  # Deploy to Cloud Run
  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'helloworld',
           '--image=europe-southwest1-docker.pkg.dev/${PROJECT_ID}/myimage:${SHORT_SHA}',
           '--region', 'europe-southwest1', '--platform', 'managed',
           '--allow-unauthenticated']

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://${_BUCKET_NAME}/
    paths:
      - ${SHORT_SHA}_test_log.xml
# Store images in Google Artifact Registry.
images:
  - europe-southwest1-docker.pkg.dev/${PROJECT_ID}/myimage:${SHORT_SHA}